Repository meetup-fe-next/daview-ui, pull requests merged in 2023-07, with the labels that each got.

#15 feat: icon 있는 버튼 스타일링 및 디자인시스템 변경 내역 반영
  components/Button/index.tsx
  stories/Button.stories.tsx
Labels: feature, style

#17 feat: input 컴포넌트 추가
  components/Icons/ArrowLeft.tsx
  components/Icons/CloseCircle.tsx
  components/Icons/IconBase.tsx
  components/Icons/Search.tsx
  components/Icons/index.ts
  components/Input.tsx
  components/Input/index.constant.ts
  components/Input/index.tsx
  stories/Input.stories.tsx
Labels: feature, style

#32 chore: tailwind config에 ui 디렉토리 추가
  tailwind.config.js
Labels: setting

#33 feat: component들에 className prop 추가
  components/Button/index.tsx
  components/Input/index.tsx
  components/Typography/Body/index.tsx
  components/Typography/Headline/index.tsx
  components/Typography/Subtitle/index.tsx
Labels: feature, refactoring

#40 feat: typo color add
  components/Typography/Body/index.tsx
  components/Typography/Headline/index.tsx
  components/Typography/Subtitle/index.tsx
  components/Typography/Typography.constants.ts
  stories/Typography/Body.stories.tsx
  stories/Typography/Headline.stories.tsx
  stories/Typography/Subtitle.stories.tsx
Labels: style

#14 feat: github markdown 추출 API
  .env.example
  README.md
  app/creators/page.tsx
  app/lectures/[id]/page.tsx
  app/lectures/page.tsx
  app/page.tsx
  app/search/page.tsx
  app/test/page.tsx
  app/typography/layout.tsx
  app/typography/page.tsx
  components/Input.tsx
  components/PageLayout/PageLayoutContents.tsx
  components/PageLayout/index.tsx
  constants/index.ts
  next.config.js
  package-lock.json
  package.json
  server/controllers/categories.ts
  server/controllers/creators.ts
  server/controllers/lectures.ts
  server/libs/algoliaSDK.ts
  server/libs/githubSdk.ts
  server/utils/common.ts
  tailwind.config.js
  types/algolia.type.ts
  types/categories.type.ts
  types/creators.type.ts
  types/github.type.ts
  types/lectures.type.ts
  ui/Test.tsx
  utils/index.ts
Labels: feature

#31 feat: 메인 페이지 레이아웃
  app/page.tsx
  components/Input/index.tsx
  ui/mainPage/GithubProfile.tsx
  ui/mainPage/MainContainer.tsx
  ui/mainPage/SearchSuggestion.tsx
Labels: style
