Repository meetup-fe-next/daview-ui, pull requests merged in 2023-06, with the labels that each got.

#3 feat: 주요 폴더 구조 생성
  components/README.md
  hooks/README.md
  ui/README.md
  utils/README.md
Labels: documentation

#11 Feature/design system button
  components/Button/index.tsx
  package-lock.json
  package.json
Labels: feature, style

#10 feat: Icon 컴포넌트 추가
  app/page.tsx
  components/Icons/ArrowLeft.tsx
  components/Icons/Heart.tsx
  components/Icons/IconBase.tsx
  components/Icons/Profile.tsx
  components/Icons/Search.tsx
  components/Icons/index.ts
Labels: feature, style

#12 feat: setup storybook
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  next.config.js
  package-lock.json
  package.json
  stories/Button.stories.tsx
  tailwind.config.js
Labels: test, setting

#18 feat:subtitle+body 추가
  app/typography/page.tsx
  components/Typography/Body/index.tsx
  components/Typography/Headline/index.tsx
  components/Typography/Subtitle/index.tsx
  package-lock.json
  tailwind.config.js
Labels: feature, style

#26 feat: storybook에서 tsconfig import alias로 절대경로 import 가능하게 수정
  .storybook/main.ts
  stories/Button.stories.tsx
Labels: test, setting

#25 feat:typography stories 추가
  app/typography/page.tsx
  stories/Typography/Body.stories.tsx
  stories/Typography/Headline.stories.tsx
  stories/Typography/Subtitle.stories.tsx
Labels: feature

#27 feat:tailwind plugin 추가
  tailwind.config.js
Labels: feature, style
